/**
 * Build config for electron main process
 */
const { resolve } = require('path');
const webpack = require('webpack');
const { mutateWebpackConfig } = require('./webpack.config.common');

/**
 * @param config {webpack.Configuration}
 */
module.exports = (config) => {
  // console.log(require('util').inspect(config, { depth: 8 }));
  mutateWebpackConfig(config);

  if (config.mode === 'development') {
    // webui is generated by another webpack process, this is the glue
    config.plugins.push(new webpack.DefinePlugin({
      __webpack_public_path__: JSON.stringify(resolve(config.output.path, '../renderer')),
      __webpack_main_path__: JSON.stringify(config.output.path)
    }));

    config.devtool = 'source-map';
  }

  config.target = 'electron-main';

  return config;
};
