import { ApplicationsAvailable } from '@src/graphql/queries';

const TMP_MOST_POP_APPS = {
  creamOfTheCropApps: [
    {
      id: 'recipe/14',
      previousServiceId: 'gmail',
      name: 'Gmail',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#e75a4d',
      iconURL: 'https://cdn.filestackcontent.com/Yxw83DJdRW2N2PkcDFGA',
      startURL:
        'https://accounts.google.com/AddSession?passive=true&Email={{userIdentity.profileData.email}}&continue=https://mail.google.com/mail/u/{{userIdentity.profileData.email}}',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/14/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/18',
      previousServiceId: 'gcalendar-mu',
      name: 'Google Calendar',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#3A82F5',
      iconURL: 'https://cdn.filestackcontent.com/SoMG9urFTpGgqP2GVsdv',
      startURL:
        'https://calendar.google.com/calendar/{{#if moreThanOneIdentity}}b/{{userIdentity.profileData.email}}{{/if}}',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/18/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/16',
      previousServiceId: 'gdrive-mu',
      name: 'Google Drive',
      category: {
        name: 'Storage & File-sharing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#FCCD48',
      iconURL: 'https://cdn.filestackcontent.com/J4MAUo7LRZm2fhyp6X0f',
      startURL:
        'https://accounts.google.com/AddSession?passive=true&Email={{userIdentity.profileData.email}}&continue=https://drive.google.com/drive/{{#if moreThanOneIdentity}}u/{{userIdentity.profileData.email}}{{/if}}',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/16/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/21',
      previousServiceId: 'slack',
      name: 'Slack',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#42C299',
      iconURL: 'https://cdn.filestackcontent.com/3xFWEVkgSEmQzEUIxGiv',
      startURL: 'https://{{subdomain}}.slack.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/21/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.slack.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/122',
      previousServiceId: 'whatsapp',
      name: 'Whatsapp',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#25D366',
      iconURL: 'https://cdn.filestackcontent.com/34oofXYQG6nVG9oXXxPI',
      startURL: 'https://web.whatsapp.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/122/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/20',
      previousServiceId: 'trello',
      name: 'Trello',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0085D3',
      iconURL: 'https://cdn.filestackcontent.com/hihkW53ARiyuRQ7yZq7o',
      startURL: 'https://trello.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/20/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/310',
      previousServiceId: 'facebook-messenger',
      name: 'Facebook Messenger',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#09F',
      iconURL: 'https://cdn.filestackcontent.com/Mx7YEqznSJ2OkCO7novG',
      startURL: 'https://www.messenger.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/310/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/25',
      previousServiceId: 'linkedIn',
      name: 'LinkedIn',
      category: {
        name: 'Social Media & Advertising',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0071A1',
      iconURL: 'https://cdn.filestackcontent.com/YAlX1QvGGulHyWhujTAX',
      startURL: 'https://www.linkedin.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/25/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/59',
      previousServiceId: 'twitter',
      name: 'Twitter',
      category: {
        name: 'Social Media & Advertising',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#1DA1F2',
      iconURL: 'https://cdn.filestackcontent.com/d8JTzPSSvS3cVL6yO62A',
      startURL: 'https://twitter.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/59/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/126',
      previousServiceId: 'telegram',
      name: 'Telegram',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#2EB7E5',
      iconURL: 'https://cdn.filestackcontent.com/I9X5pOO7TeacxmJvsP60',
      startURL: 'https://web.telegram.org',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/126/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/104',
      previousServiceId: 'evernote',
      name: 'Evernote',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#7AC143',
      iconURL: 'https://cdn.filestackcontent.com/uxqqrNpfRT6Uei1lH96Q',
      startURL: 'https://www.evernote.com/Home.action',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/104/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/156',
      previousServiceId: 'google-keep',
      name: 'Google Keep',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#F6B500',
      iconURL: 'https://cdn.filestackcontent.com/8GXSa0qvQUW6xkGEsgcq',
      startURL:
        'https://keep.google.com/{{#if moreThanOneIdentity}}u/{{userIdentity.profileData.email}}{{/if}}',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/156/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/388',
      previousServiceId: 'instagram',
      name: 'Instagram',
      category: {
        name: 'Social Media & Advertising',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#E43966',
      iconURL: 'https://cdn.filestackcontent.com/1Ob9MEgzSMqVSZZF6wY0',
      startURL: 'https://www.instagram.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/388/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/39',
      previousServiceId: 'github',
      name: 'GitHub',
      category: {
        name: 'Developer Tools',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#221E1B',
      iconURL: 'https://cdn.filestackcontent.com/ML2wP9JLS7WwJE4nOf3w',
      startURL: 'https://github.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/39/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/140',
      previousServiceId: 'outlook',
      name: 'Outlook',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0070C9',
      iconURL: 'https://cdn.filestackcontent.com/XdVhfkeSZyYeRGAc3yc3',
      startURL: 'https://outlook.live.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/140/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/34',
      previousServiceId: 'asana',
      name: 'Asana',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#F95B82',
      iconURL: 'https://cdn.filestackcontent.com/b1goeyaVQM2lQA0PNE5b',
      startURL: 'https://app.asana.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/34/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/69',
      previousServiceId: 'dropbox',
      name: 'Dropbox',
      category: {
        name: 'Storage & File-sharing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#007EE5',
      iconURL: 'https://cdn.filestackcontent.com/zwo14IIeT1yAZdQwgwuG',
      startURL: 'https://www.dropbox.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/69/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/138',
      previousServiceId: 'skype',
      name: 'Skype',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#00AFF0',
      iconURL: 'https://cdn.filestackcontent.com/3oVsMqx0TT2klDcIBv3k',
      startURL: 'https://web.skype.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/138/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/100',
      previousServiceId: 'atlassian',
      name: 'Atlassian (Jira, Confluence..)',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#264970',
      iconURL: 'https://cdn.filestackcontent.com/Ch2raiH5Q0W7Dx6RD32p',
      startURL: 'https://{{subdomain}}.atlassian.net/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/100/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.atlassian.net',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/115',
      previousServiceId: 'google-hangouts',
      name: 'Hangouts',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#82B750',
      iconURL: 'https://cdn.filestackcontent.com/jYO38GpXTlWHrZ36Cd0M',
      startURL: 'https://hangouts.google.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/115/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
  ] as ApplicationsAvailable[],
  runnerUps: [
    {
      id: 'recipe/391',
      previousServiceId: 'icloud',
      name: 'iCloud',
      category: {
        name: 'Storage & File-sharing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#3a9df4',
      iconURL: 'https://cdn.filestackcontent.com/pn92JMsJTmmyKMvTLhYZ',
      startURL: 'https://www.icloud.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/391/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/261',
      previousServiceId: 'zoom-us',
      name: 'Zoom',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#2D8CFF',
      iconURL: 'https://cdn.filestackcontent.com/f8cBB3XlTRCkjJAtL6F7',
      startURL: 'https://zoom.us/signin',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/261/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/187',
      previousServiceId: 'canva',
      name: 'Canva',
      category: {
        name: 'Design & Creativity',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#18B9C1',
      iconURL: 'https://cdn.filestackcontent.com/yPtdEx8RW2Tbajyq4Sbp',
      startURL: 'https://www.canva.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/187/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/134',
      previousServiceId: 'toggl',
      name: 'Toggl',
      category: {
        name: 'HR & Legal',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#E41317',
      iconURL: 'https://cdn.filestackcontent.com/2bBLLqqTUeBQ1arzX50S',
      startURL: 'https://toggl.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/134/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/394',
      previousServiceId: 'paypal',
      name: 'Paypal',
      category: {
        name: 'Accounting & Finance',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#149cd4',
      iconURL: 'https://cdn.filestackcontent.com/W7vLMuZ6SRmCuVuD3bT5',
      startURL: 'https://www.paypal.com/signin',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/394/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/123',
      previousServiceId: 'gitlab',
      name: 'Gitlab',
      category: {
        name: 'Developer Tools',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#E24329',
      iconURL: 'https://cdn.filestackcontent.com/hMPbjRpcRleMWdplfmfK',
      startURL: 'https://gitlab.com/users/sign_in',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/123/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/181',
      previousServiceId: '1password-backoffice',
      name: '1Password',
      category: {
        name: 'Admin & Back-office',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#2175FF',
      iconURL: 'https://cdn.filestackcontent.com/X7bGS8xQG2Da3brzvsgo',
      startURL: 'https://my.1password.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/181/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/64',
      previousServiceId: 'hubspot',
      name: 'Hubspot',
      category: {
        name: 'Sales & CRM',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#DF662B',
      iconURL: 'https://cdn.filestackcontent.com/HDBMMXgT96KAXw5if2RJ',
      startURL: 'https://app.hubspot.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/64/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/478',
      previousServiceId: 'amazon',
      name: 'Amazon',
      category: {
        name: 'Curation & Sourcing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#fc9c04',
      iconURL: 'https://cdn.filestackcontent.com/OKnXQQEfTCS82Ae83Guc',
      startURL: 'https://amazon.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/478/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/214',
      previousServiceId: 'google-contact',
      name: 'Google Contact',
      category: {
        name: 'Sales & CRM',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#3054BC',
      iconURL: 'https://cdn.filestackcontent.com/rO1qr1SOyxaJtNUaSaQL',
      startURL: 'https://contacts.google.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/214/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/40',
      previousServiceId: 'mailchimp',
      name: 'Mailchimp',
      category: {
        name: 'Marketing & Analytics',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#FFCA00',
      iconURL: 'https://cdn.filestackcontent.com/3YblQVApTatFB87Dfa5M',
      startURL: 'https://admin.mailchimp.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/40/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/379',
      previousServiceId: 'wechat',
      name: 'WeChat',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#2DC100',
      iconURL: 'https://cdn.filestackcontent.com/I3Y4l7hoSNmJZFxlKh0R',
      startURL: 'https://web.wechat.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/379/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/23',
      previousServiceId: 'intercom',
      name: 'Intercom',
      category: {
        name: 'Sales & CRM',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#1F8DED',
      iconURL: 'https://cdn.filestackcontent.com/Y6GmxbvTQCHxRC6jhsKA',
      startURL: 'https://app.intercom.io',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/23/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/404',
      previousServiceId: 'udemy',
      name: 'Udemy',
      category: {
        name: 'Miscellaneous',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#ec5454',
      iconURL: 'https://cdn.filestackcontent.com/Sklz24ovQlq6D7ugQpJV',
      startURL: 'https://www.udemy.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/404/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/116',
      previousServiceId: 'wordpress',
      name: 'Wordpress',
      category: {
        name: 'Blogging & Content Creation',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0087BE',
      iconURL: 'https://cdn.filestackcontent.com/nBmsLYHeQrK1j1Gj3qRT',
      startURL: 'https://wordpress.com/wp-login.php',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/116/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/35',
      previousServiceId: 'google-adwords',
      name: 'Google Ads',
      category: {
        name: 'Social Media & Advertising',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4285F4',
      iconURL: 'https://cdn.filestackcontent.com/Pb8eVvJESNmyqDWYrTG5',
      startURL: 'https://adwords.google.com/um/Welcome/Home?',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/35/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/303',
      previousServiceId: 'zeplin',
      name: 'Zeplin',
      category: {
        name: 'Design & Creativity',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#F89920',
      iconURL: 'https://cdn.filestackcontent.com/0pxvMMXQt6j5uYDLDfRw',
      startURL: 'https://app.zeplin.io/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/303/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/125',
      previousServiceId: 'fb-workplace',
      name: 'Facebook Workplace',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#373F4D',
      iconURL: 'https://cdn.filestackcontent.com/P0MEIe0OQE2vcRheBFpP',
      startURL: 'https://{{subdomain}}.facebook.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/125/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.facebook.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/401',
      previousServiceId: 'soundcloud',
      name: 'SoundCloud',
      category: {
        name: 'Miscellaneous',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#f4640c',
      iconURL: 'https://cdn.filestackcontent.com/7cGtj06gTW6kLOg2cuSI',
      startURL: 'https://soundcloud.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/401/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/378',
      previousServiceId: 'clickup',
      name: 'ClickUp',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#7B68EE',
      iconURL: 'https://cdn.filestackcontent.com/ZerZczISRSb7wyR5HyOL',
      startURL: 'https://app.clickup.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/378/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/119',
      previousServiceId: 'aws-account',
      name: 'Amazon AWS',
      category: {
        name: 'Developer Tools',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#F68D11',
      iconURL: 'https://cdn.filestackcontent.com/A76IE80oQuyj0CtOWtOl',
      startURL: 'https://{{subdomain}}.signin.aws.amazon.com/console',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/119/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.signin.aws.amazon.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/62',
      previousServiceId: 'zendesk2',
      name: 'Zendesk',
      category: {
        name: 'User Support & Survey',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#00363E',
      iconURL: 'https://cdn.filestackcontent.com/bhdHUbarSoSoC75ieViz',
      startURL: 'https://{{subdomain}}.zendesk.com/agent',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/62/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.zendesk.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/38',
      previousServiceId: 'salesforce',
      name: 'Salesforce',
      category: {
        name: 'Sales & CRM',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#00A1E0',
      iconURL: 'https://cdn.filestackcontent.com/qwJ6L2SvQIOry3P2ZCxs',
      startURL: 'https://login.salesforce.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/38/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/595',
      previousServiceId: 'backlog',
      name: 'Backlog',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4ccca4',
      iconURL: 'https://cdn.filestackcontent.com/L9hpfddHQMqDgomTHOoi',
      startURL: 'https://{{subdomain}}.backlog.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/595/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.backlog.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/299',
      previousServiceId: 'meet',
      name: 'Meet',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#009585',
      iconURL: 'https://cdn.filestackcontent.com/3WaVDBFxRPWKJy1iGRPO',
      startURL: 'https://meet.google.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/299/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/73',
      previousServiceId: 'box',
      name: 'Box',
      category: {
        name: 'Storage & File-sharing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0075C9',
      iconURL: 'https://cdn.filestackcontent.com/6cr3gowdQ2qKmjwsNGbl',
      startURL: 'https://account.box.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/73/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/529',
      previousServiceId: 'yahoo-email',
      name: 'Yahoo Email',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4c0c94',
      iconURL: 'https://cdn.filestackcontent.com/PidRuthS34AFc82TYn9Q',
      startURL: 'https://mail.yahoo.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/529/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/145',
      previousServiceId: 'dropbox-paper',
      name: 'Dropbox Paper',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#007EE5',
      iconURL: 'https://cdn.filestackcontent.com/xgfftrTaRJSuR6ePS33h',
      startURL: 'https://paper.dropbox.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/145/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/94',
      previousServiceId: 'dribbble',
      name: 'Dribbble',
      category: {
        name: 'Design & Creativity',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#EA4988',
      iconURL: 'https://cdn.filestackcontent.com/0Mr0rCB1TbWP8ARR9g5R',
      startURL: 'https://dribbble.com/session/new',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/94/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/385',
      previousServiceId: 'monday',
      name: 'Monday',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#F91B50',
      iconURL: 'https://cdn.filestackcontent.com/3ow8MIvBSvK7n6ysLDRg',
      startURL: 'https://{{subdomain}}.monday.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/385/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.monday.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/563',
      previousServiceId: 'stackoverflow',
      name: 'StackOverflow',
      category: {
        name: 'Developer Tools',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#f48424',
      iconURL: 'https://cdn.filestackcontent.com/hb3OR2S9RvWXhJU20hUH',
      startURL: 'https://stackoverflow.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/563/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/402',
      previousServiceId: 'ifttt',
      name: 'IFTTT',
      category: {
        name: 'Miscellaneous',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#049cfc',
      iconURL: 'https://cdn.filestackcontent.com/7O3ROZ3RKmhbcJUAOp47',
      startURL: 'https://ifttt.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/402/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/213',
      previousServiceId: 'microsoft-todo',
      name: 'Microsoft ToDo',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4B7CF2',
      iconURL: 'https://cdn.filestackcontent.com/CohGM9YaTJSBdE7IsLcK',
      startURL: 'https://todo.microsoft.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/213/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/99',
      previousServiceId: 'zapier',
      name: 'Zapier',
      category: {
        name: 'Miscellaneous',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#FF4A00',
      iconURL: 'https://cdn.filestackcontent.com/AwJ5KJxWS1TIfEPFEXWA',
      startURL: 'https://zapier.com/app/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/99/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/410',
      previousServiceId: 'draw-io',
      name: 'Draw.io',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#f48c04',
      iconURL: 'https://cdn.filestackcontent.com/k2dghL1TneYwqJxM4kMJ',
      startURL: 'https://www.draw.io/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/410/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/422',
      previousServiceId: 'unsplash',
      name: 'Unsplash',
      category: {
        name: 'Design & Creativity',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#000000',
      iconURL: 'https://cdn.filestackcontent.com/t61I7miATe25IIyroqsQ',
      startURL: 'https://unsplash.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/422/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/201',
      previousServiceId: 'wetransfer',
      name: 'Wetransfer',
      category: {
        name: 'Storage & File-sharing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0092D0',
      iconURL: 'https://cdn.filestackcontent.com/hOpvT9HTnyZWusub1If0',
      startURL: 'https://wetransfer.com/sign-in',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/201/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/87',
      previousServiceId: 'basecamp',
      name: 'Basecamp',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#66CC66',
      iconURL: 'https://cdn.filestackcontent.com/sBL5CRfZQYqJwEdx7CPg',
      startURL: 'https://3.basecamp.com/sign_in',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/87/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/246',
      previousServiceId: 'google-webmaster',
      name: 'Google Search Console',
      category: {
        name: 'Admin & Back-office',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4089F8',
      iconURL: 'https://cdn.filestackcontent.com/G0SURHVZTEOtLk7dMgiB',
      startURL: 'https://www.google.com/webmasters/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/246/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/415',
      previousServiceId: 'boomerang',
      name: 'Boomerang',
      category: {
        name: 'Sales & CRM',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4a4a4a',
      iconURL: 'https://cdn.filestackcontent.com/GkU5gEL0SPW9Bfnp3ZQL',
      startURL: null,
      isChromeExtension: true,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/415/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/382',
      previousServiceId: 'behance',
      name: 'Behance',
      category: {
        name: 'Design & Creativity',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0056FE',
      iconURL: 'https://cdn.filestackcontent.com/VzZqsmY3RrG3nPwGeFdn',
      startURL: 'https://www.behance.net/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/382/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/112',
      previousServiceId: 'stripe',
      name: 'Stripe',
      category: {
        name: 'Accounting & Finance',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#00A0DE',
      iconURL: 'https://cdn.filestackcontent.com/Ka0dYZbNSmGKmRMa2CQ4',
      startURL: 'https://dashboard.stripe.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/112/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/343',
      previousServiceId: 'producthunt',
      name: 'ProductHunt',
      category: {
        name: 'Curation & Sourcing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#DA552F',
      iconURL: 'https://cdn.filestackcontent.com/0azETKerQKiUJoUuNOTG',
      startURL: 'https://www.producthunt.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/343/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/332',
      previousServiceId: 'harvest',
      name: 'Harvest',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#FF7400',
      iconURL: 'https://cdn.filestackcontent.com/ZEXiDuivS9ONy9dYNVGw',
      startURL: 'https://id.getharvest.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/332/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/51',
      previousServiceId: 'bufferapp',
      name: 'Buffer',
      category: {
        name: 'Social Media & Advertising',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#000000',
      iconURL: 'https://cdn.filestackcontent.com/Sk3I08KXTeWxgnWUr2fR',
      startURL: 'https://buffer.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/51/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/550',
      previousServiceId: 'protonmail',
      name: 'Proton Mail',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#1E213F',
      iconURL: 'https://cdn.filestackcontent.com/kMqInOmTOuMJwO1VqlBA',
      startURL: 'https://mail.proton.me',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/550/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/615',
      previousServiceId: 'google-music',
      name: 'Google Music ',
      category: {
        name: 'Miscellaneous',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#fccc1b',
      iconURL: 'https://cdn.filestackcontent.com/FziR86KhQQOlvapE3VQL',
      startURL: 'http://music.google.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/615/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/380',
      previousServiceId: 'firebase',
      name: 'Firebase',
      category: {
        name: 'Developer Tools',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#FCC338',
      iconURL: 'https://cdn.filestackcontent.com/NGoB7lJSH2ftuu1rCeMg',
      startURL: 'https://console.firebase.google.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/380/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
  ] as ApplicationsAvailable[],
  noteworthy: [
    {
      id: 'recipe/391',
      previousServiceId: 'icloud',
      name: 'iCloud',
      category: {
        name: 'Storage & File-sharing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#3a9df4',
      iconURL: 'https://cdn.filestackcontent.com/pn92JMsJTmmyKMvTLhYZ',
      startURL: 'https://www.icloud.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/391/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/261',
      previousServiceId: 'zoom-us',
      name: 'Zoom',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#2D8CFF',
      iconURL: 'https://cdn.filestackcontent.com/f8cBB3XlTRCkjJAtL6F7',
      startURL: 'https://zoom.us/signin',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/261/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/187',
      previousServiceId: 'canva',
      name: 'Canva',
      category: {
        name: 'Design & Creativity',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#18B9C1',
      iconURL: 'https://cdn.filestackcontent.com/yPtdEx8RW2Tbajyq4Sbp',
      startURL: 'https://www.canva.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/187/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/134',
      previousServiceId: 'toggl',
      name: 'Toggl',
      category: {
        name: 'HR & Legal',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#E41317',
      iconURL: 'https://cdn.filestackcontent.com/2bBLLqqTUeBQ1arzX50S',
      startURL: 'https://toggl.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/134/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/394',
      previousServiceId: 'paypal',
      name: 'Paypal',
      category: {
        name: 'Accounting & Finance',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#149cd4',
      iconURL: 'https://cdn.filestackcontent.com/W7vLMuZ6SRmCuVuD3bT5',
      startURL: 'https://www.paypal.com/signin',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/394/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/123',
      previousServiceId: 'gitlab',
      name: 'Gitlab',
      category: {
        name: 'Developer Tools',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#E24329',
      iconURL: 'https://cdn.filestackcontent.com/hMPbjRpcRleMWdplfmfK',
      startURL: 'https://gitlab.com/users/sign_in',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/123/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/181',
      previousServiceId: '1password-backoffice',
      name: '1Password',
      category: {
        name: 'Admin & Back-office',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#2175FF',
      iconURL: 'https://cdn.filestackcontent.com/X7bGS8xQG2Da3brzvsgo',
      startURL: 'https://my.1password.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/181/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/64',
      previousServiceId: 'hubspot',
      name: 'Hubspot',
      category: {
        name: 'Sales & CRM',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#DF662B',
      iconURL: 'https://cdn.filestackcontent.com/HDBMMXgT96KAXw5if2RJ',
      startURL: 'https://app.hubspot.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/64/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/478',
      previousServiceId: 'amazon',
      name: 'Amazon',
      category: {
        name: 'Curation & Sourcing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#fc9c04',
      iconURL: 'https://cdn.filestackcontent.com/OKnXQQEfTCS82Ae83Guc',
      startURL: 'https://amazon.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/478/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/214',
      previousServiceId: 'google-contact',
      name: 'Google Contact',
      category: {
        name: 'Sales & CRM',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#3054BC',
      iconURL: 'https://cdn.filestackcontent.com/rO1qr1SOyxaJtNUaSaQL',
      startURL: 'https://contacts.google.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/214/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/40',
      previousServiceId: 'mailchimp',
      name: 'Mailchimp',
      category: {
        name: 'Marketing & Analytics',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#FFCA00',
      iconURL: 'https://cdn.filestackcontent.com/3YblQVApTatFB87Dfa5M',
      startURL: 'https://admin.mailchimp.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/40/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/379',
      previousServiceId: 'wechat',
      name: 'WeChat',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#2DC100',
      iconURL: 'https://cdn.filestackcontent.com/I3Y4l7hoSNmJZFxlKh0R',
      startURL: 'https://web.wechat.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/379/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/23',
      previousServiceId: 'intercom',
      name: 'Intercom',
      category: {
        name: 'Sales & CRM',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#1F8DED',
      iconURL: 'https://cdn.filestackcontent.com/Y6GmxbvTQCHxRC6jhsKA',
      startURL: 'https://app.intercom.io',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/23/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/404',
      previousServiceId: 'udemy',
      name: 'Udemy',
      category: {
        name: 'Miscellaneous',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#ec5454',
      iconURL: 'https://cdn.filestackcontent.com/Sklz24ovQlq6D7ugQpJV',
      startURL: 'https://www.udemy.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/404/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/116',
      previousServiceId: 'wordpress',
      name: 'Wordpress',
      category: {
        name: 'Blogging & Content Creation',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0087BE',
      iconURL: 'https://cdn.filestackcontent.com/nBmsLYHeQrK1j1Gj3qRT',
      startURL: 'https://wordpress.com/wp-login.php',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/116/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/35',
      previousServiceId: 'google-adwords',
      name: 'Google Ads',
      category: {
        name: 'Social Media & Advertising',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4285F4',
      iconURL: 'https://cdn.filestackcontent.com/Pb8eVvJESNmyqDWYrTG5',
      startURL: 'https://ads.google.com/aw/overview',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/35/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/303',
      previousServiceId: 'zeplin',
      name: 'Zeplin',
      category: {
        name: 'Design & Creativity',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#F89920',
      iconURL: 'https://cdn.filestackcontent.com/0pxvMMXQt6j5uYDLDfRw',
      startURL: 'https://app.zeplin.io/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/303/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/125',
      previousServiceId: 'fb-workplace',
      name: 'Facebook Workplace',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#373F4D',
      iconURL: 'https://cdn.filestackcontent.com/P0MEIe0OQE2vcRheBFpP',
      startURL: 'https://{{subdomain}}.facebook.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/125/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.facebook.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/401',
      previousServiceId: 'soundcloud',
      name: 'SoundCloud',
      category: {
        name: 'Miscellaneous',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#f4640c',
      iconURL: 'https://cdn.filestackcontent.com/7cGtj06gTW6kLOg2cuSI',
      startURL: 'https://soundcloud.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/401/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/378',
      previousServiceId: 'clickup',
      name: 'ClickUp',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#7B68EE',
      iconURL: 'https://cdn.filestackcontent.com/ZerZczISRSb7wyR5HyOL',
      startURL: 'https://app.clickup.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/378/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/119',
      previousServiceId: 'aws-account',
      name: 'Amazon AWS',
      category: {
        name: 'Developer Tools',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#F68D11',
      iconURL: 'https://cdn.filestackcontent.com/A76IE80oQuyj0CtOWtOl',
      startURL: 'https://{{subdomain}}.signin.aws.amazon.com/console',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/119/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.signin.aws.amazon.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/62',
      previousServiceId: 'zendesk2',
      name: 'Zendesk',
      category: {
        name: 'User Support & Survey',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#00363E',
      iconURL: 'https://cdn.filestackcontent.com/bhdHUbarSoSoC75ieViz',
      startURL: 'https://{{subdomain}}.zendesk.com/agent',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/62/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.zendesk.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/38',
      previousServiceId: 'salesforce',
      name: 'Salesforce',
      category: {
        name: 'Sales & CRM',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#00A1E0',
      iconURL: 'https://cdn.filestackcontent.com/qwJ6L2SvQIOry3P2ZCxs',
      startURL: 'https://login.salesforce.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/38/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/595',
      previousServiceId: 'backlog',
      name: 'Backlog',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4ccca4',
      iconURL: 'https://cdn.filestackcontent.com/L9hpfddHQMqDgomTHOoi',
      startURL: 'https://{{subdomain}}.backlog.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/595/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.backlog.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/299',
      previousServiceId: 'meet',
      name: 'Meet',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#009585',
      iconURL: 'https://cdn.filestackcontent.com/3WaVDBFxRPWKJy1iGRPO',
      startURL: 'https://meet.google.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/299/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/73',
      previousServiceId: 'box',
      name: 'Box',
      category: {
        name: 'Storage & File-sharing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0075C9',
      iconURL: 'https://cdn.filestackcontent.com/6cr3gowdQ2qKmjwsNGbl',
      startURL: 'https://account.box.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/73/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/529',
      previousServiceId: 'yahoo-email',
      name: 'Yahoo Email',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4c0c94',
      iconURL: 'https://cdn.filestackcontent.com/PidRuthS34AFc82TYn9Q',
      startURL: 'https://mail.yahoo.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/529/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/145',
      previousServiceId: 'dropbox-paper',
      name: 'Dropbox Paper',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#007EE5',
      iconURL: 'https://cdn.filestackcontent.com/xgfftrTaRJSuR6ePS33h',
      startURL: 'https://paper.dropbox.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/145/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/94',
      previousServiceId: 'dribbble',
      name: 'Dribbble',
      category: {
        name: 'Design & Creativity',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#EA4988',
      iconURL: 'https://cdn.filestackcontent.com/0Mr0rCB1TbWP8ARR9g5R',
      startURL: 'https://dribbble.com/session/new',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/94/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/385',
      previousServiceId: 'monday',
      name: 'Monday',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#F91B50',
      iconURL: 'https://cdn.filestackcontent.com/3ow8MIvBSvK7n6ysLDRg',
      startURL: 'https://{{subdomain}}.monday.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/385/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: true,
      preconfigurations: {
        onpremise: false,
        subdomain: '.monday.com',
        __typename: 'Preconfigurations',
      },
      __typename: 'Application',
    },
    {
      id: 'recipe/563',
      previousServiceId: 'stackoverflow',
      name: 'StackOverflow',
      category: {
        name: 'Developer Tools',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#f48424',
      iconURL: 'https://cdn.filestackcontent.com/hb3OR2S9RvWXhJU20hUH',
      startURL: 'https://stackoverflow.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/563/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/402',
      previousServiceId: 'ifttt',
      name: 'IFTTT',
      category: {
        name: 'Miscellaneous',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#049cfc',
      iconURL: 'https://cdn.filestackcontent.com/7O3ROZ3RKmhbcJUAOp47',
      startURL: 'https://ifttt.com/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/402/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/213',
      previousServiceId: 'microsoft-todo',
      name: 'Microsoft ToDo',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4B7CF2',
      iconURL: 'https://cdn.filestackcontent.com/CohGM9YaTJSBdE7IsLcK',
      startURL: 'https://todo.microsoft.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/213/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/99',
      previousServiceId: 'zapier',
      name: 'Zapier',
      category: {
        name: 'Miscellaneous',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#FF4A00',
      iconURL: 'https://cdn.filestackcontent.com/AwJ5KJxWS1TIfEPFEXWA',
      startURL: 'https://zapier.com/app/login',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/99/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/410',
      previousServiceId: 'draw-io',
      name: 'Draw.io',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#f48c04',
      iconURL: 'https://cdn.filestackcontent.com/k2dghL1TneYwqJxM4kMJ',
      startURL: 'https://www.draw.io/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/410/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/422',
      previousServiceId: 'unsplash',
      name: 'Unsplash',
      category: {
        name: 'Design & Creativity',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#000000',
      iconURL: 'https://cdn.filestackcontent.com/t61I7miATe25IIyroqsQ',
      startURL: 'https://unsplash.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/422/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/201',
      previousServiceId: 'wetransfer',
      name: 'Wetransfer',
      category: {
        name: 'Storage & File-sharing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0092D0',
      iconURL: 'https://cdn.filestackcontent.com/hOpvT9HTnyZWusub1If0',
      startURL: 'https://wetransfer.com/sign-in',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/201/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/87',
      previousServiceId: 'basecamp',
      name: 'Basecamp',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#66CC66',
      iconURL: 'https://cdn.filestackcontent.com/sBL5CRfZQYqJwEdx7CPg',
      startURL: 'https://launchpad.37signals.com/signin',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/87/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/246',
      previousServiceId: 'google-webmaster',
      name: 'Google Search Console',
      category: {
        name: 'Admin & Back-office',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4089F8',
      iconURL: 'https://cdn.filestackcontent.com/G0SURHVZTEOtLk7dMgiB',
      startURL: 'https://www.google.com/webmasters/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/246/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/415',
      previousServiceId: 'boomerang',
      name: 'Boomerang',
      category: {
        name: 'Sales & CRM',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#4a4a4a',
      iconURL: 'https://cdn.filestackcontent.com/GkU5gEL0SPW9Bfnp3ZQL',
      startURL: null,
      isChromeExtension: true,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/415/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/382',
      previousServiceId: 'behance',
      name: 'Behance',
      category: {
        name: 'Design & Creativity',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#0056FE',
      iconURL: 'https://cdn.filestackcontent.com/VzZqsmY3RrG3nPwGeFdn',
      startURL: 'https://www.behance.net/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/382/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/112',
      previousServiceId: 'stripe',
      name: 'Stripe',
      category: {
        name: 'Accounting & Finance',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#00A0DE',
      iconURL: 'https://cdn.filestackcontent.com/Ka0dYZbNSmGKmRMa2CQ4',
      startURL: 'https://dashboard.stripe.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/112/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/343',
      previousServiceId: 'producthunt',
      name: 'ProductHunt',
      category: {
        name: 'Curation & Sourcing',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#DA552F',
      iconURL: 'https://cdn.filestackcontent.com/0azETKerQKiUJoUuNOTG',
      startURL: 'https://www.producthunt.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/343/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/332',
      previousServiceId: 'harvest',
      name: 'Harvest',
      category: {
        name: 'Task & Project Management',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#FF7400',
      iconURL: 'https://cdn.filestackcontent.com/ZEXiDuivS9ONy9dYNVGw',
      startURL: 'https://id.getharvest.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/332/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/51',
      previousServiceId: 'bufferapp',
      name: 'Buffer',
      category: {
        name: 'Social Media & Advertising',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#000000',
      iconURL: 'https://cdn.filestackcontent.com/Sk3I08KXTeWxgnWUr2fR',
      startURL: 'https://buffer.com/',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/51/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/550',
      previousServiceId: 'protonmail',
      name: 'Proton Mail',
      category: {
        name: 'Communication & Collaboration',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#1E213F',
      iconURL: 'https://cdn.filestackcontent.com/kMqInOmTOuMJwO1VqlBA',
      startURL: 'https://mail.proton.me',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/550/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/615',
      previousServiceId: 'google-music',
      name: 'Google Music ',
      category: {
        name: 'Miscellaneous',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#fccc1b',
      iconURL: 'https://cdn.filestackcontent.com/FziR86KhQQOlvapE3VQL',
      startURL: 'http://music.google.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/615/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
    {
      id: 'recipe/380',
      previousServiceId: 'firebase',
      name: 'Firebase',
      category: {
        name: 'Developer Tools',
        __typename: 'ApplicationCategory',
      },
      themeColor: '#FCC338',
      iconURL: 'https://cdn.filestackcontent.com/NGoB7lJSH2ftuu1rCeMg',
      startURL: 'https://console.firebase.google.com',
      isChromeExtension: false,
      bxAppManifestURL:
        'http://localhost:4001/application-recipe/380/bxAppManifest.json',
      isPrivate: null,
      isPreconfigurable: false,
      preconfigurations: null,
      __typename: 'Application',
    },
  ] as ApplicationsAvailable[],
};

export { TMP_MOST_POP_APPS };
