import { StationApp } from './app/types';
import { ApplicationsSettings } from './application-settings/types';
import { StationApplications } from './applications/types';
import { Extensions } from './chrome-extensions/types';
import { DialogItems } from './dialogs/types';
import { StationDock } from './dock/types';
import { StationFavorites } from './favorites/types';
import { StationHistory } from './history/get';
import { StationNav } from './nav/types';
import { StationNotification } from './notification-center/types';
import { StationNotifications } from './notifications/types';
import { StationServicesData } from './plugins/types';
import { StationAllOrderedTabs } from './ordered-tabs/types';
import { StationAllOrderedFavorites } from './ordered-favorites/types';
import { StationTabs } from './tabs/types';
import { StationTheme } from './theme/types';
import { StationUi } from './ui/types';
import { StationUserIdentities } from './user-identities/types';

export type StationRawState = {
  tabs: StationTabs;
  userIdentities: StationUserIdentities;
  applications: StationApplications;
  nav: StationNav;
  history: StationHistory;
  applicationSettings: ApplicationsSettings;
  dialogs: DialogItems;
  chromeExtensions: Extensions;
  dock: StationDock;
  app: StationApp;
  favorites: StationFavorites;
  theme: StationTheme;
  subwindows: string[];
  ui: StationUi;
  notifications: StationNotifications;
  notificationCenter: StationNotification;
  servicesData: StationServicesData;
  orderedTabs: StationAllOrderedTabs;
  orderedFavorites: StationAllOrderedFavorites;
  // TODO
  downloads: any;
  dlToaster: any[];
  auto_update: any;
  onboarding: any;
  user: any;
  appStore: any;
  bang: any;
  OSBar: any;
  tabWebcontents: any;
  inTabSearch: any;
  subdock: any;
  windows: any;
  teamApp: any;
  userActivities: any[];
  deepIntegrationSlack: any;
  passwordManagers: any;
  passwordManagerLinks: any;
  defaultServices: any;
  plugins: any;
};
