export const WEIGHT_FUSE = 100;
export const WEIGHT_CONTEXTUAL_FRECENCY = 2;
export const WEIGHT_GLOBAL_FRECENCY = 2;

export const WEIGHT_CONTEXTUAL_FRECENCY_RECENT_SELECTIONS_MATCH = 0.1;
export const WEIGHT_GLOBAL_FRECENCY_RECENT_SELECTIONS_MATCH = 1.0;
