export enum ElectronAppPath {
  Home = 'home',
  AppData = 'appData',
  UserData = 'userData',
  Temp = 'temp',
  Exe = 'exe',
  Module = 'module',
  Desktop = 'desktop',
  Documents = 'documents',
  Downloads = 'downloads',
  Music = 'music',
  Pictures = 'pictures',
  Videos = 'videos',
  Logs = 'logs',
  PepperFlashSystemPlugin = 'pepperFlashSystemPlugin',
}
